### ISSUE TITLE
Обернуть все в функцию

### ISSUE THREAD

**Issue by magakoos** [carusalgiz/practicePyCourses#2]
https://github.com/carusalgiz/practicePyCourses/blob/601667eb10f4699669bba56d9524f70675b1d807/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0%202%20-%20%D0%A4%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8.py#L8

Обернуть все в функцию и добавить ее вызов в конце.

**Comment by carusalgiz** [comment]
функция есть, вызов ее тоже есть. можно чуть подробнее, что не так?

**Comment by bigman212** [comment]
@carusalgiz возможно @magakoos говорит про этакий "main" в Python. http://www.codenet.ru/webmast/python/
